## Tabular Data Homework

In [1]:
import os
import numpy

In [10]:
water_file = os.path.join('data','water.xyz')
outlist = numpy.genfromtxt(fname = water_file, skip_header = 2, dtype = 'unicode')
print(outlist)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [11]:
atoms = outlist[:,0]
print(atoms)

['O' 'H1' 'H2']


In [12]:
coords = outlist [:, 1:]
print(coords)

[['0.000000' '-0.007156' '0.965491']
 ['-0.000000' '0.001486' '-0.003471']
 ['0.000000' '0.931026' '1.207929']]


In [13]:
coords = coords.astype(numpy.float)
print(coords)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [14]:
num_atoms = len(atoms)
for i in range (0, num_atoms):
    for j in range (0, num_atoms):
        x_length = coords[i,0]-coords[j,0]
        y_length = coords[i,1]-coords[j,1]
        z_length = coords[i,2]-coords[j,2]
        bond_length = numpy.sqrt(x_length**2+y_length**2+z_length**2)
        print(F'{atoms[i]} to {atoms[j]} : {bond_length:.3f}')
        

O to O : 0.000
O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H1 to H1 : 0.000
H1 to H2 : 1.527
H2 to O : 0.969
H2 to H1 : 1.527
H2 to H2 : 0.000
